### ISSUE TITLE
Add `sinktest/base.GetRowCountWithPredicate()` helper

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/replicator#689]
We have several cases where test code wants a variation on the existing `GetRowCount()`, but needs to add a substitution parameter or two. We should have some way of moving per-target complexity out of the individual tests.

**Comment by ryanluu12345** [comment]
What are example tests that can benefit from this enhancement? Where exactly should I look for this?

**Comment by bobvawter** [comment]
`git grep -i 'select count'`

https://github.com/cockroachdb/replicator/blob/master/internal/sequencer/script/script_test.go#L200-L211
