### ISSUE TITLE
go 1.22 cleanup: Remove for-loop capture variables

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/replicator#757]
https://tip.golang.org/doc/go1.22 see section "References to loop variables"

**Comment by ryanluu12345** [comment]
As a note I did a global search in the repository for for loops and went through most of these files and didn't see capture variables. I usually see that the index variable is used to index within a slice (i.e. mutations[i]). Wondering if this is still relevant?

**Comment by bobvawter** [comment]
```
% git rev-parse --short HEAD
b8af3ae1

bob@crlMBP-F763D71VCFMTcx:~/cdc-sink
% git grep -i capture
.github/workflows/go-tests.yaml:      # Capture container logs in case they're needed for diagnostics.
internal/target/apply/apply_test.go:            tc := tc // Capture for t.Parallel().
internal/util/lockset/lockset_test.go:          i := i // Capture
```

Certainly less relevant than it was.

**Comment by ryanluu12345** [comment]
Easy fix here. Fixed the remaining ones here: https://github.com/cockroachdb/replicator/pull/1066/files
